# Variables are case sensitive.
[Fst, TStart]          : 0.
[Fst, TMax]            : 30.
[Fst, OutFileFmt]      : 1
[Fst, DT]              : 0.005
[ServoDyn, DLL_DT]     : 0.005

# [InflowWind, WindType] : 1
# [InflowWind, HWindSpeed] : 9.

[Fst, CompSub]         : 0
[Fst, CompServo]         : 0
[Fst, CompHydro]         : 0

[ElastoDyn, PtfmSgDOF] : False
[ElastoDyn, PtfmSwDOF] : False
[ElastoDyn, PtfmHvDOF] : False
[ElastoDyn, PtfmRDOF]  : False
[ElastoDyn, PtfmPDOF]  : False
[ElastoDyn, PtfmYDOF]  : False

[ElastoDyn, YawDOF]   : False
[ElastoDyn, FlapDOF1] : False
[ElastoDyn, FlapDOF2] : False
[ElastoDyn, EdgeDOF]  : False
[ElastoDyn, DrTrDOF]  : False
[ElastoDyn, GenDOF]   : False
[ElastoDyn, TwFADOF1] : False
[ElastoDyn, TwFADOF2] : False
[ElastoDyn, TwSSDOF1] : False
[ElastoDyn, TwSSDOF2] : False


[ElastoDyn, BlPitch(1)] : 0.
[ElastoDyn, BlPitch(2)] : 0.
[ElastoDyn, BlPitch(3)] : 0.
[ElastoDyn, RotSpeed]   : 6.394
[InflowWind, PLexp]   : 0.0

[ServoDyn, PCMode]     : 0
[ServoDyn, VSContrl]   : 0
[ServoDyn, YCMode]     : 0
[AeroDyn15, WakeMod]   : 1
[AeroDyn15, AFAeroMod] : 2
[AeroDyn15, TwrPotent] : 0
[AeroDyn15, TwrShadow] : False
[AeroDyn15, TwrAero]   : False
[AeroDyn15, SkewMod]   : 2
[AeroDyn15, TipLoss]   : True
[AeroDyn15, HubLoss]   : True
[AeroDyn15, TanInd]  : True
[AeroDyn15, AIDrag]  : True
[AeroDyn15, TIDrag]  : True
[AeroDyn15, IndToler]  : 1.e-5
[AeroDyn15, MaxIter]  : 5000
[AeroDyn15, UseBlCm] : True
